//! The one door to a shell.
//!
//! `ns` is somebody's login shell, so the interesting question is not how to
//! get to bash but how to make sure this is the *only* way. Everything else in
//! the CLI is built so that no operator input reaches a shell: pipe modifiers
//! are functions, `ping` and `traceroute` exec their binaries with an argv,
//! and there is no `!`, no backtick and no `$(...)`.
//!
//! This is the exception, and it is deliberate, gated and audited:
//!
//! - configd decides whether it is allowed, and records it against the uid it
//!   read from `SO_PEERCRED` -- not a uid this process claimed
//! - it is not reachable from configuration mode, where an operator has
//!   uncommitted work
//! - bash runs as the operator's own uid; nothing here elevates anything
//!
//! # The rcfile
//!
//! bash is started with a generated rcfile that sources the operator's normal
//! startup files, defines `operational` as a way back, and sets a prompt that
//! says where they are. Sourcing their own files first matters: a shell that
//! ignores somebody's aliases is a shell they will work around.

use std::io::Write;
use std::process::Command;

use tempfile::NamedTempFile;

#[derive(Debug, thiserror::Error)]
pub enum ShellError {
    #[error("preparing the shell: {0}")]
    Prepare(#[from] std::io::Error),

    #[error("/bin/bash could not be started: {0}")]
    Start(String),
}

/// The rcfile bash is started with.
///
/// Written out rather than passed on a command line because it is a program,
/// and because `--rcfile` is the only way to get bash to run something before
/// an interactive session without pretending to be a login shell.
fn rcfile() -> String {
    // Single-quoted PS1 so nothing in it is expanded when the file is sourced;
    // bash expands the escapes itself at prompt time.
    r#"# Generated by Nightshade for this shell session. Not persistent.

# The operator's own environment first. A shell that ignores somebody's
# aliases is a shell they will work around.
[ -r /etc/bash.bashrc ] && . /etc/bash.bashrc
[ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"

# The way back. `exit` and Ctrl-D do the same thing; this exists because
# "operational" is what the prompt can tell somebody to type.
operational() { exit; }

PS1='\u@\h:\w (shell - type '\''operational'\'' to return)\$ '
"#
    .to_string()
}

/// Drop to bash and come back.
///
/// Blocks until the shell exits. The `ns` process is still here the whole
/// time, so history, mode and any candidate configuration are exactly as they
/// were left.
pub fn run() -> Result<(), ShellError> {
    let mut file = NamedTempFile::new()?;
    file.write_all(rcfile().as_bytes())?;
    file.flush()?;

    // An argv, never a string. There is no shell interpreting this line --
    // which is the whole point of a program whose job is to be the only way to
    // reach one.
    let status = Command::new("/bin/bash")
        .arg("--rcfile")
        .arg(file.path())
        .arg("-i")
        .status()
        .map_err(|e| ShellError::Start(e.to_string()))?;

    // Kept alive until bash has finished reading it.
    drop(file);

    if !status.success() {
        // A shell that exits non-zero is an operator who typed `exit 1`, not
        // an error worth reporting to them.
        return Ok(());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_rcfile_defines_the_way_back() {
        let rc = rcfile();
        assert!(rc.contains("operational() { exit; }"), "{rc}");
        assert!(rc.contains("type '\\''operational'\\'' to return"), "{rc}");
    }

    #[test]
    fn the_rcfile_sources_the_operators_own_startup_files() {
        let rc = rcfile();
        assert!(rc.contains(". /etc/bash.bashrc"), "{rc}");
        assert!(rc.contains(r#". "$HOME/.bashrc""#), "{rc}");
    }

    /// The prompt has to survive being sourced without expanding early, or an
    /// operator's working directory is frozen at the moment they typed
    /// `shell`.
    #[test]
    fn the_prompt_is_single_quoted_so_bash_expands_it_at_prompt_time() {
        let rc = rcfile();
        let line = rc
            .lines()
            .find(|line| line.starts_with("PS1="))
            .expect("a PS1 line");
        assert!(line.starts_with("PS1='"), "{line}");
        assert!(line.contains(r"\u@\h:\w"), "{line}");
    }
}
