[package]
name = "nightshade-render"
description = "Renders a Nightshade config into systemd-networkd and system state"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
nightshade-common = { workspace = true }
nightshade-schema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
